//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPXViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class KmlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KmlSettings defaultInstance = ((KmlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KmlSettings())));
        
        public static KmlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%temp%\\gpxviewer.kml")]
        public string KmlFileName {
            get {
                return ((string)(this["KmlFileName"]));
            }
            set {
                this["KmlFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double IconScale {
            get {
                return ((double)(this["IconScale"]));
            }
            set {
                this["IconScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff")]
        public string TrkAlpha {
            get {
                return ((string)(this["TrkAlpha"]));
            }
            set {
                this["TrkAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff0000")]
        public string TrkColor {
            get {
                return ((string)(this["TrkColor"]));
            }
            set {
                this["TrkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RAINBOW")]
        public string TrkColorMode {
            get {
                return ((string)(this["TrkColorMode"]));
            }
            set {
                this["TrkColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double TrkLineWidth {
            get {
                return ((double)(this["TrkLineWidth"]));
            }
            set {
                this["TrkLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTrkIcon {
            get {
                return ((bool)(this["UseTrkIcon"]));
            }
            set {
                this["UseTrkIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTrkTrack {
            get {
                return ((bool)(this["UseTrkTrack"]));
            }
            set {
                this["UseTrkTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTrkLines {
            get {
                return ((bool)(this["UseTrkLines"]));
            }
            set {
                this["UseTrkLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.google.com/mapfiles/kml/pushpin/wht-pushpin.png")]
        public string TrkIconUrl {
            get {
                return ((string)(this["TrkIconUrl"]));
            }
            set {
                this["TrkIconUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff")]
        public string RteAlpha {
            get {
                return ((string)(this["RteAlpha"]));
            }
            set {
                this["RteAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000ff")]
        public string RteColor {
            get {
                return ((string)(this["RteColor"]));
            }
            set {
                this["RteColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COLOR")]
        public string RteColorMode {
            get {
                return ((string)(this["RteColorMode"]));
            }
            set {
                this["RteColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double RteLineWidth {
            get {
                return ((double)(this["RteLineWidth"]));
            }
            set {
                this["RteLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRteIcon {
            get {
                return ((bool)(this["UseRteIcon"]));
            }
            set {
                this["UseRteIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.google.com/mapfiles/kml/paddle/wht-circle.png")]
        public string RteIconUrl {
            get {
                return ((string)(this["RteIconUrl"]));
            }
            set {
                this["RteIconUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff")]
        public string WptAlpha {
            get {
                return ((string)(this["WptAlpha"]));
            }
            set {
                this["WptAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffcc66")]
        public string WptColor {
            get {
                return ((string)(this["WptColor"]));
            }
            set {
                this["WptColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COLOR")]
        public string WptColorMode {
            get {
                return ((string)(this["WptColorMode"]));
            }
            set {
                this["WptColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double WptLineWidth {
            get {
                return ((double)(this["WptLineWidth"]));
            }
            set {
                this["WptLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseWptIcon {
            get {
                return ((bool)(this["UseWptIcon"]));
            }
            set {
                this["UseWptIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.google.com/mapfiles/kml/paddle/wht-circle.png")]
        public string WptIconUrl {
            get {
                return ((string)(this["WptIconUrl"]));
            }
            set {
                this["WptIconUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromptToOverwrite {
            get {
                return ((bool)(this["PromptToOverwrite"]));
            }
            set {
                this["PromptToOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendToGoogleEarth {
            get {
                return ((bool)(this["SendToGoogleEarth"]));
            }
            set {
                this["SendToGoogleEarth"] = value;
            }
        }
    }
}
